language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script:
  - mv config/database.yml{.travis,}
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate spec
before_script:
  - psql -c 'create database call4paperz_test' -U postgres
